// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKeQ0iyPvCgOBqRYBV9QYSX6-jP2L4hrw',
    appId: '1:645697704156:android:7950d49ceb01689beba419',
    messagingSenderId: '645697704156',
    projectId: 'smokingapp-623e2',
    storageBucket: 'smokingapp-623e2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMsZjZD6MjiEbFakNyj6zq4ACn6Yti59k',
    appId: '1:645697704156:web:489ae9d08cfdf2f6eba419',
    messagingSenderId: '645697704156',
    projectId: 'smokingapp-623e2',
    authDomain: 'smokingapp-623e2.firebaseapp.com',
    storageBucket: 'smokingapp-623e2.firebasestorage.app',
    measurementId: 'G-ZJGLMBT04E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqbWURKT8WrPI1mx6FnVX-ch30FgEBZgs',
    appId: '1:645697704156:ios:dfc4e8ae95db647eeba419',
    messagingSenderId: '645697704156',
    projectId: 'smokingapp-623e2',
    storageBucket: 'smokingapp-623e2.firebasestorage.app',
    iosBundleId: 'com.example.reduceSmokingApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqbWURKT8WrPI1mx6FnVX-ch30FgEBZgs',
    appId: '1:645697704156:ios:dfc4e8ae95db647eeba419',
    messagingSenderId: '645697704156',
    projectId: 'smokingapp-623e2',
    storageBucket: 'smokingapp-623e2.firebasestorage.app',
    iosBundleId: 'com.example.reduceSmokingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMsZjZD6MjiEbFakNyj6zq4ACn6Yti59k',
    appId: '1:645697704156:web:5ca5a852fe7537deeba419',
    messagingSenderId: '645697704156',
    projectId: 'smokingapp-623e2',
    authDomain: 'smokingapp-623e2.firebaseapp.com',
    storageBucket: 'smokingapp-623e2.firebasestorage.app',
    measurementId: 'G-TZVN2N32SC',
  );

}